### ISSUE TITLE
[fix] 2-1 AuthForm.jsx

### ISSUE THREAD

**Issue by JudyCCC** [obrm/react-best-practices-design-pattens#1]
https://github.com/obrm/react-best-practices-design-pattens/blob/master/2-separation-of-concerns/1-custom-hooks/components/AuthForm.jsx#L43

```js
if (isLogin && label === 'User name') return null;

const { label, type, name, value, onChange } = input;
```

should be:
```js
const { label, type, name, value, onChange } = input;

if (isLogin && label === 'User name') return null;
```

The `label` field should be used after parsing.

Friendly reminder: The example code does not match the screenshot in the article.

Finally, thank you very much for writing this article, which has benefited a lot. Can I translate it into Chinese and share it? (I will mark the source of the article)

**Comment by obrm** [comment]
Thank you very much! I fixed it!
Of course you can translate this article.

I'd be very glad!
